pretranslate:
  segments:
    ignore_patterns:
    - "Native"
    - "^(title|authors|date|description): "
  paths:
  - source: "src/site/content/en/angular"
    include:
    - "**/index.md"
    - "accessible-angular-with-codelyzer/index.md"
settings:
  ignore_escaped_strings: true
